version: '3.7'
services:
  ppac-postgres-local:
    image: postgres:11.12-alpine
    container_name: ppac-postgres-local
    restart: always
    environment:
      POSTGRES_DB: postgres-local
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5434:5432'
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge