version: '3.7'
services:
  ppac-mariadb-local:
    image: mariadb:10.6.14
    container_name: ppac-mariadb-local
    restart: always
    environment:
      MARIADB_DATABASE: mariadb-local
      MARIADB_USER: db_admin
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge