CREATE TABLE  IF NOT EXISTS CODES
(
    ID        UUID     PRIMARY KEY,
    VALUE     INTEGER  UNIQUE CHECK (VALUE BETWEEN 100000 AND 999999),
    CODE_TYPE VARCHAR(12) CHECK (CODE_TYPE IN ('ADMIN_CODE','COMPANY_CODE'))
);

CREATE TABLE  IF NOT EXISTS COMPANIES
(
    ID           UUID  PRIMARY KEY,
    DISPLAY_NAME VARCHAR(30) NOT NULL,
    FULL_NAME    VARCHAR(50) DEFAULT NULL,
    LOGO         BYTEA DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS COMPANIES_CODES
(
    CODE_ID  UUID  NOT NULL,
    VALUE  INTEGER NOT NULL UNIQUE CHECK (VALUE BETWEEN 100000 AND 999999),
    COMPANY_ID UUID NOT NULL,
    FOREIGN KEY (CODE_ID) REFERENCES CODES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (VALUE) REFERENCES CODES(VALUE) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


