CREATE TABLE CODES
(
    ID        UUID         NOT NULL PRIMARY KEY,
    VALUE     VARCHAR(255) NOT NULL UNIQUE,
    CODE_TYPE VARCHAR(7)   NOT NULL,
    COMPANY_ID UUID

);

CREATE TABLE COMPANIES
(
    ID           UUID         NOT NULL PRIMARY KEY,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    FULL_NAME    VARCHAR(255),
    LOGO         BYTEA
);

