
ALTER TABLE IF EXISTS COMPANIES
DROP COLUMN FULL_NAME;

ALTER TABLE IF EXISTS COMPANIES
RENAME COLUMN DISPLAY_NAME TO NAME;

ALTER TABLE IF EXISTS COMPANIES
ADD COLUMN DESCRIPTION VARCHAR(300) DEFAULT NULL UNIQUE;

ALTER TABLE IF EXISTS COMPANIES
ADD COLUMN EMAIL VARCHAR(50) DEFAULT NULL UNIQUE;


