CREATE TABLE IF NOT EXISTS COMPANIES_OPENINGS (
    COMPANY_ENTITY_ID   UUID  NOT NULL UNIQUE,
    OPENINGS_ID  UUID  NOT NULL UNIQUE,
    FOREIGN KEY (COMPANY_ENTITY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (OPENINGS_ID) REFERENCES OPENINGS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (COMPANY_ENTITY_ID, OPENINGS_ID)
    );