CREATE TABLE  IF NOT EXISTS COMPANIES_OPENINGS (
    ID UUID PRIMARY KEY,
    COMPANY_ID   UUID  NOT NULL UNIQUE,
    OPENING_ID  UUID  NOT NULL UNIQUE,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (OPENING_ID) REFERENCES OPENINGS(ID) ON DELETE CASCADE ON UPDATE CASCADE
    );