feature:
  mvp: true

sql:
  instance: localhost:3306
  database: mariadb-local
  schema: mariadb-local
  db-admin-username: db_admin
  db-admin-password: mariadb
  app-admin-username: db_admin
  app-admin-password: mariadb
  read-write-username: db_admin
  read-write-password: mariadb
  read-only-username: db_admin
  read-only-password: mariadb
  business-read-only-username: db_admin
  business-read-only-password: mariadb

  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      generate_statistics: false
    org:
      hibernate:
        envers:
          audit_table_suffix: _audit_log