server:
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: NEVER
    include-exception: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

feature:
  mvp: false
  ppac-v1: false
  ppac-service: false

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  flyway:
    enabled: false
  config:
    use-legacy-processing: true